### PR TITLE
Unify the Configuration of Triton Accounts

### PR DESCRIPTION
**Pull request by stack72**
Currently, the Terraform triton provider would support configuration via 2 methods:

* Specifying a SSH Key ID meaning that it would search in the SSH Agent
* Passing the contents of a private key as the KeyMaterial

It was missing a 3rd way of configuring, passing a key path and letting the terraform provider get the contents for itself

This means we are now starting to be more consistent in how we configure the triton provider

//cc @cheapRoc

### CODE REVIEW

**Comment by jen20** [comment]
FWIW this _was_ supported and then deprecated as part of the push to stop Terraform reading files for itself in favour of the `file` interpolation, back in the Terraform 0.6-0.7 days. That said, people have the path configured in their environment there is value to reviving it, so :+1.

**Comment by cheapRoc** [comment]
👍 I feel like this enhances usability. We've had a recent issue (#40) around configuration so PRs like this help.

**Comment by stack72** [comment]
@cheapRoc / @jen20 also, the reason I realised this had to still be supported was when working with SolEng for the Minio work. They didn't know about SSH Agents so still wanted to read SSH Key details using a path

**Comment by cheapRoc** [comment]
@stack72 Your point makes me think this could be handy in `triton-go` as a helper function. Though I'm still in favor of `triton-go` [defaulting to SSH agent](https://github.com/joyent/triton-go/blob/master/client/client.go#L79) authentication. 

Worth mentioning that I've done some work around guarding this default case while adding unit tests (branch still in flux [here](https://github.com/cheapRoc/triton-go/commits/f-unit-tests)). Maybe this is worth merging in and adding the better `SDC_KEY_MATERIAL` support as a utility for reuse?

**Comment by stack72** [comment]
@cheapRoc I think we can merge this now and then we can decide about a helper in triton-go 

Right now, this doesn't change any of the default behaviour :)

**Pull request merged**
