### PR TITLE
triton_machine: Introduce CNS stanza and better domain name tracking

### PR DESCRIPTION
**Pull request by cheapRoc**
Ref: #8 #4 and #3

This implements the CNS stanza outlined in [#8(comment)](https://github.com/terraform-providers/terraform-provider-triton/issues/8#issuecomment-316175311). This touches both `tags` as well as moving `cns` related configuration into its own block. 

Things to note:

- CNS is enabled by having the CNS block and its `services` argument.
- I’ve maintained naming and feature parity with the `disable` feature. If `disable` is true, than all CNS related configuration is ignored and DNS names are cleared from the resource’s state (more on this below).
- `disable` feature only works on update, it is hard set to false during provisioning.
- It took time to get right but I’ve implemented proper DNS name state handling. The provider will wait for DNS names to converge, checking to make sure domains exist for each CNS service label.
- Since CNS arguments are actually tags under the Triton API, it made sense to piggy back off the existing `tags` handling.

### Domain Names

It’s worth talking about how CNS domain names converge….

The process for waiting on domain name convergence is rather naive and simply checks for domain names that include each service name as the first part of the domain name, (`frontend` -> `frontend.svc.<uuid>.us-west-1.triton.zone`). We only check the first part of the DNS record (`frontend.`) and only look for a single domain match (because CNS works for both private, public, and either/or). From all of my tests, this convergence feature has been working really well and takes about 20 seconds. There is no timeout.

Please make sure when testing that you are looking at both CNS tags as well as domain names stored in the state file. I kept a list of [various combinations of state](https://gist.github.com/cheapRoc/4efe9a0e1c3a067bc8484e8b2be150f8) that I found while buckling down the hatches of CNS.

### Finally

I'd like to handle the final merge alongside #14 since those will affect each other. I could open a PR with both included together if that makes it easier to merge into master.

### CODE REVIEW

**Comment by cheapRoc** [comment]
Actually, realized I forgot to commit tests. Probably should flesh those out.

**Comment by cheapRoc** [comment]
This should be at least good to test and review. I'm looking at the hash comparison again but feeling confident its doing the job ATM.

**Comment by cheapRoc** [comment]
Close this PR once #17 has been merged. #17 includes both CNS and Metadata features.

**Comment by jen20** [comment]
Subsumed into #17.

**Pull request closed without merging**
