### PR TITLE
[MODULES] Switch to Go Modules

### LINKED ISSUE #120: [PROPOSAL] Switch to Go Modules
As part of the preparation for Terraform v0.12, we would like to migrate all providers to use [Go Modules](https://github.com/golang/go/wiki/Modules). We plan to continue checking dependencies into vendor/ to remain compatible with existing tooling/CI for a period of time, however go modules will be used for management. Go Modules is the official solution for the go programming language, we understand some providers might not want this change yet, however we encourage providers to begin looking towards the switch as this is how we will be managing all Go projects in the future. Would maintainers please react with :+1: for support, or :-1: if you wish to have this provider omitted from the first wave of pull requests. If your provider is in support, we would ask that you avoid merging any pull requests that mutate the dependencies while the Go Modules PR is open (in fact a total codefreeze would be even more helpful), otherwise we will need to close that PR and re-run `go mod init`. Once merged, dependencies can be added or updated as follows:

```
$ GO111MODULE=on go get github.com/some/module@master
$ GO111MODULE=on go mod tidy
$ GO111MODULE=on go mod vendor
```

GO111MODULE=on might be unnecessary depending on your environment, this example will fetch a module @ master and record it in your project's go.mod and go.sum files. It's a good idea to tidy up afterward and then copy the dependencies into vendor/. To remove dependencies from your project, simply remove all usage from your codebase and run:

```
$ GO111MODULE=on go mody tidy
$ GO111MODULE=on go mod vendor
```

Thank you sincerely for all your time, contributions, and cooperation!

### PR DESCRIPTION
**Pull request by appilon**
Closes #120

### CODE REVIEW

**Comment by appilon** [comment]
some acceptance tests need investigation

**Comment by appilon** [comment]
the tests seem to be flaky, can't tell if anything has regressed. Could you look at the latest build for the `go-modules-2019-02-22` branch, it says it has only 1 new failure (a flaky test), however it has 12 failing tests, on master there is only 10 failing tests (and 3 new 🤔) I don't know how this branch can report only 1 new failing test? `12 - 10 = 1???`

**Comment by radeksimko** [comment]
@appilon I'm don't know how exactly does TeamCity count number of "new" failing tests, but these seem like genuine failures which aren't seen in `master` so they may need some attention:

```
=== RUN   TestAccTritonFabricNetwork_BadArguments
--- FAIL: TestAccTritonFabricNetwork_BadArguments (0.00s)
    testing.go:531: Step 0, expected error:
        
        config is invalid: data.triton_fabric_network.test: "vlan_id" value must be between 0 and 4095
        
        To match:
        
        .* \\"vlan_id\\" value must be between 0 and 4095
=== RUN   TestAccTritonFabricNetwork_MissingArguments
--- FAIL: TestAccTritonFabricNetwork_MissingArguments (0.01s)
    testing.go:531: Step 0, expected error:
        
        config is invalid: 2 problems:
        
        - data.triton_fabric_network.test: "name": required field is not set
        - data.triton_fabric_network.test: "vlan_id": required field is not set
        
        To match:
        
        .* \\"name\\": .* \\"vlan_id\\": .* field is not set.*
=== RUN   TestAccTritonFabricVLAN_BadArguments
--- FAIL: TestAccTritonFabricVLAN_BadArguments (0.00s)
    testing.go:531: Step 0, expected error:
        
        config is invalid: data.triton_fabric_vlan.test: "vlan_id" value must be between 0 and 4095
        
        To match:
        
        .* \\"vlan_id\\" value must be between 0 and 4095
```

**Comment by appilon** [comment]
@radeksimko I will investigate thank you!

**Comment by Smithx10** [comment]
Is there anything holding this up?  I've got a few users that want to use it with TF 12,  and I've got some cycles available.

**Comment by Smithx10** [comment]
Who is the maintainer of this repo?  Is it Hashicorp?

**Comment by siepkes** [comment]
@Smithx10 FYI I made the following [post](https://smartdatacenter.topicbox.com/groups/sdc-discuss/Te66ebc92537e4754/state-and-future-of-the-terraform-triton-provider) yesterday on the Triton mailinglist which might be of interest to you.

**Comment by teamterraform** [comment]
Hi folks,
There is an ongoing discussion about the maintainer-ship of this provider internally at HashiCorp and with Joyent.

We will post updates when we have them. Thank you for your patience in the meantime.

**Comment by nwilkens** [comment]
I would love to see some movement on this, @teamterraform how can we move this forward?

**Comment by pannon** [comment]
Same here, we rely on the Terraform provider and for example this bug is a
showstopper
https://github.com/terraform-providers/terraform-provider-triton/issues/108

Would be good to fix it up before the provider becomes unmaintainable. The
there is not many other mature and feature rich alternatives out there for
non Docker instances.

**Pull request merged**
